### ISSUE TITLE
False positive finding for `WRONG_INDENTATION`

### ISSUE THREAD

**Issue by WebTiger89** [saveourtool/diktat#1312]
When running diktatCheck I get a false-positive finding for the following code snippet:
```kt
            Surface(
                modifier = Modifier.fillMaxSize(),
                color = MaterialTheme.colors.background,
            ) {
                Text("Android")
            }
```
Warning: expected 20 but was 16
So it expects:
```kt
            Surface(
                    modifier = Modifier.fillMaxSize(),
                    color = MaterialTheme.colors.background,
            ) {
                Text("Android")
            }
```
Maybe this is Jetpack Compose specific and you want to adjust the rule in this direction.

**Comment by akuleshov7** [comment]
Thank you for you report! It is very confusing, but it should be working. We will check asap!

**Comment by akuleshov7** [comment]
@WebTiger89 hm, I checked it in our online demo and it works fine...

![image](https://user-images.githubusercontent.com/58667063/170710821-254d8e09-b1a3-4aa6-9c1f-300b3ec737a9.png)

**Comment by akuleshov7** [comment]
Which version are you using? May be code snippet is more complex?

**Comment by WebTiger89** [comment]
Damn I checked the diktat-analysis.yml file and by default `extendedIndentOfParameters` is true
```
    # If true: in parameter list when parameters are split by newline they are indented with two indentations instead of one
    extendedIndentOfParameters: true
```
When I disable it, it works at this point like expected :)

**Comment by WebTiger89** [comment]
You might want to adjust the default setting. Can be closed. Thanks for the fast support :)

**Comment by akuleshov7** [comment]
> `extendedIndentOfParameters`

yeah, that is the legacy support for old IDEAs :)

**Comment by akuleshov7** [comment]
> You might want to adjust the default setting. 
Exactly! Thank you for catching that! We forgot to revert an example

**Comment by WebTiger89** [comment]
Sorry I have to reopen this. While example above is not reported anymore after setting `extendedIndentOfParameters: false` in config file. Everything else is still reported. When I opened the issue I checked only a small part of the code but now I'm running the check over hundred of files so I noticed it only now.

Example:
```
fun YoutubeChip(selected: Boolean, text: String, modifier: Modifier = Modifier) {
    Surface(
        color = when {
            selected -> MaterialTheme.colors.onSurface
            else -> Color.Transparent
        },
    )
}
```

> [WRONG_INDENTATION] only spaces are allowed for indentation and each indentation should equal to 4 spaces (tabs are not allowed): expected 12 but was 8

etc.

Ktlint online reports it too.

Here the whole rule of my config file:
```
# Checks that indentation is correct
- name: WRONG_INDENTATION
  enabled: true
  configuration:
    # Is newline at the end of a file needed
    newlineAtEnd: true
    # If true: in parameter list when parameters are split by newline they are indented with two indentations instead of one
    extendedIndentOfParameters: false
    # If true: if first parameter in parameter list is on the same line as opening parenthesis, then other parameters can be aligned with it
    alignedParameters: true
    # If true: if expression is split by newline after operator like +/-/`*`, then the next line is indented with two indentations instead of one
    extendedIndentAfterOperators: true
    # The indentation size for each file
    indentationSize: 4
```

**Comment by WebTiger89** [comment]
I might figured out on which code snippets it fails mainly. It seems 2 specific cases can not be handled properly:
1. Expression bodies
2. Jetpack Compose Modifier moved to next line

Example for 1:
```
 val currentTime: Time
    get() =
            with(currentDateTime) {
                Time(hour = hour, minute = minute, second = second)
            }
```
or
```
fun formatDateByPattern(date: String, pattern: String = "ddMMyy"): String =
    DateTimeFormatter.ofPattern(pattern).format(LocalDate.parse(date))
```
or
```
fun LocalDateTime.updateTime(
    hour: Int? = null,
    minute: Int? = null,
    second: Int? = null,
): LocalDateTime = withHour(hour ?: getHour())
    .withMinute(minute ?: getMinute())
    .withSecond(second ?: getSecond())
```
Example for 2:
```
Box(
	Modifier
		.align(Alignment.CenterVertically)
		.widthIn(min = 16.dp + 40.dp),
	contentAlignment = Alignment.CenterStart,
)
```

**Comment by 0x6675636b796f75676974687562** [comment]
@WebTiger89, thank you for your feedback.

I'm looking into the issue and will get back to you in a short while.

**Comment by akuleshov7** [comment]
> fun formatDateByPattern(date: String, pattern: String = "ddMMyy"): String =
>    DateTimeFormatter.ofPattern(pattern).format(LocalDate.parse(date)) 

code provided by @WebTiger89 is a legacy issue in IDEA - I have described it here:
https://github.com/saveourtool/diktat/issues/1323#issuecomment-1141146584
They have partially fixed it and we need to support this logic

**Comment by 0x6675636b796f75676974687562** [comment]
@WebTiger89, today we've made a minor fix (0706885e1eeb0b185853d0e2d0f2bf4fc73238bd) which may affect your experience. From now on, `extendedIndentOfParameters` defaults to `false` even if there's no config file available.

Apart from that, your first example is correct:

```kotlin
@Composable
fun YoutubeChip(selected: Boolean, text: String, modifier: Modifier = Modifier) {
    Surface(
        color = when {
            selected -> MaterialTheme.colors.onSurface
            else -> Color.Transparent
        },
    )
}
```

&mdash; and consistent with the indentation config you've provided:

```yaml
- name: WRONG_INDENTATION
  enabled: true
  configuration:
    newlineAtEnd: true
    extendedIndentOfParameters: false
    alignedParameters: true
    extendedIndentAfterOperators: true
    indentationSize: 4
```

If you change the value of `extendedIndentOfParameters` to `true` (the previous behaviour), the code would need to be reformatted to become

```kotlin
@Composable
fun YoutubeChip(selected: Boolean, text: String, modifier: Modifier = Modifier) {
    Surface(
            color = when {
                selected -> MaterialTheme.colors.onSurface
                else -> Color.Transparent
            },
    )
}
```

&mdash; note that I've increased the indentation in lines 4 through 7: the 4-line `color` expressions is a function parameter and needs to be indented.

Additional examples you've supplied are affected by other flags in the `WRONG_INDENTATION`:

* `alignedParameters`,
* `extendedIndentAfterOperators`, and
* `extendedIndentBeforeDot`.

I'll provide the detailed feedback for each example tomorrow morning. Yet, the way DiKTat's indentation checker behaves looks good to me, I don't see any issues so far.
