### ISSUE TITLE
The literals used to `@Suppress` Diktat checks should be configurable via `diktat-analysis.yml`

### ISSUE THREAD

**Issue by 0x6675636b796f75676974687562** [saveourtool/diktat#1628]
The literals used to `@Suppress` _Diktat_ checks should be configurable via `diktat-analysis.yml`, e.g.:

```yaml
- name: MAGIC_NUMBER
  aliases: [ MagicNumber ]
  enabled: true
```

## Environment information
* diktat version: **1.2.4.2**

## Related

 - #1627

@nulls, feel free to comment.
