### ISSUE TITLE
Diktat 2.0 doesn't apply `diktat-analysis.yml` in sub-project

### ISSUE THREAD

**Issue by nulls** [saveourtool/diktat#1827]
Tested with `MAGIC_NUMBER` in frontend using gradle plugin

**Comment by nulls** [comment]
Actually, configuration is invalid:
```yml
- name: MAGIC_NUMBER
  enabled: true

  # reduces speed of development on the FE
  # will remove it by for now
- name: MAGIC_NUMBER
  enabled: false
```

It contains two configurations: one enabled, the second one -- disables it
